"""Render documentation/cleaning_rules.md (from config) and reports/cleaning_report.md (from real metrics).

* documentation/cleaning_rules.md is generated from config/data_quality.yaml, so every rule that the
  pipeline runs is documented with its action, correction/fallback and rationale - a rule cannot be
  added without appearing here.
* reports/cleaning_report.md is generated from reports/cleaning_metrics_<mode>.json (written by
  clean_data.py) and, if present, the idempotency check.

Usage: python spark_jobs/cleaning_report.py --mode full
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from spark_jobs.dq_rules import load_dq_config  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def rules_doc(cfg: dict) -> str:
    P = cfg["params"]
    L = ["# Cleaning Rules", "",
         "_Generated from `config/data_quality.yaml` by `spark_jobs/cleaning_report.py` - edit the YAML, not this file._", "",
         "Every data-quality rule has exactly one cleaning action:", "",
         "| action | meaning |", "|---|---|",
         "| **correct** | replace the value with a *deterministic* derivation from other fields (never a guess); if that is impossible the row gets the rule's **fallback** action |",
         "| **flag** | keep the row, add the rule ID to its `dq_flags` column so analyses can include or exclude it |",
         "| **remove** | drop the row - only used for exact duplicates of a row that is kept |",
         "| **quarantine** | move the row to `/urbantransit/clean_quarantine/<table>/` with its original content; it cannot be trusted or fixed |", "",
         "Principle: prefer **flag** or **quarantine** whenever a correction would be a guess. Every action is written to the "
         "cleaning log (`/urbantransit/cleaning_log/`, Parquet): record key, issue, rule, original value, corrected value, "
         "final status.", "",
         "| rule | defect type | table | severity | action | correction | fallback | rationale |",
         "|---|---|---|---|---|---|---|---|"]
    for r in cfg["rules"]:
        corr = r.get("correction", {})
        corr_txt = ", ".join(f"{k}={v}" for k, v in corr.items()) if corr else "-"
        L.append(f"| {r['id']} | {r['defect_type']} | {r['table']} | {r['severity']} | **{r['action']}** | {corr_txt} | "
                 f"{r.get('fallback', '-') if r['action'] == 'correct' else '-'} | {r['rationale']} |")
    L += ["", "## Thresholds (from `params`)", "", "| parameter | value |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in P.items() if k != "minimum_volumes"]
    L += ["", "## Rows quarantined at ingestion (Phase 2)", "",
          "Rows that failed type parsing in Phase 2 are re-read in Phase 3. If `correct` rules repair every column that failed "
          "(for example `delay_minutes` recomputed from the two timestamps, DQ11), the row is recovered into the clean data "
          "and logged as corrected; otherwise it stays quarantined with the matching rule IDs (or `INGESTION_TYPE_FAILURE`).", "",
          "## Using the flags downstream", "",
          "`dq_flags` is an array column in every clean table. Examples: exclude `DQ16` rows from trip-level joins "
          "(their trip record is missing); exclude `DQ20` rows from revenue totals; exclude `DQ01` trips from O-D "
          "completeness statistics.", ""]
    return "\n".join(L)


def report(mode: str) -> str:
    m = json.loads((PROJECT_ROOT / "reports" / f"cleaning_metrics_{mode}.json").read_text())
    idem_path = PROJECT_ROOT / "reports" / f"cleaning_idempotency_{mode}.json"
    L = [f"# Cleaning Report - `{mode}` dataset", "",
         f"_Generated by `spark_jobs/cleaning_report.py` from `reports/cleaning_metrics_{mode}.json` "
         f"(run log `{m['log_file']}`, {m['seconds']:.0f} s). Rules and reasons: "
         "[documentation/cleaning_rules.md](../documentation/cleaning_rules.md)._", "",
         "## Reconciliation per table", "",
         "`rows in` = Phase 2 Parquet rows + rows quarantined at ingestion.", "",
         "| table | rows in | clean | removed | quarantined | clean + removed + quarantined | reconciled | flagged (kept) | corrected | recovered from ingestion quarantine |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for t in m["tables"]:
        s = t["rows_clean"] + t["rows_removed"] + t["rows_quarantined"]
        L.append(f"| {t['table']} | {t['rows_in']:,} | {t['rows_clean']:,} | {t['rows_removed']:,} | {t['rows_quarantined']:,} | "
                 f"{s:,} | {'PASS' if t['reconciled'] else 'FAIL'} | {t['rows_flagged']:,} | {t['rows_corrected']:,} | "
                 f"{t['recovered_from_ingestion_quarantine']:,} |")
    L += ["", "## Rows per rule and action", "",
          "| table | rule | hits | corrected | flagged | removed | quarantined | recovered from ingestion quarantine |",
          "|---|---|---|---|---|---|---|---|"]
    for t in m["tables"]:
        for rid, c in sorted(t["rules"].items()):
            L.append(f"| {t['table']} | {rid} | {c.get('hits', 0):,} | {c.get('correct', 0):,} | {c.get('flag', 0):,} | "
                     f"{c.get('remove', 0):,} | {c.get('quarantine', 0):,} | {c.get('recovered_from_ingestion_quarantine', 0):,} |")
    if m["minimums"]:
        L += ["", "## Minimum volumes after cleaning", "", "| table | minimum | clean rows | result |", "|---|---|---|---|"]
        L += [f"| {k} | {v['minimum']:,} | {v['clean_rows']:,} | {'PASS' if v['ok'] else 'FAIL'} |" for k, v in m["minimums"].items()]
    L += ["", "## Cleaning log", "",
          f"`/urbantransit{'' if mode == 'full' else '_' + mode}/cleaning_log/` (Parquet, partitioned by table): "
          f"**{m['cleaning_log_rows']:,}** rows.", "",
          "| table | rule | action | log rows |", "|---|---|---|---|"]
    L += [f"| {c['table']} | {c['rule_id']} | {c['action']} | {c['rows']:,} |" for c in m["cleaning_log_counts"]]
    if idem_path.exists():
        idem = json.loads(idem_path.read_text())
        L += ["", "## Idempotency (rerun)", "", f"Second run compared with the first: **{idem['result']}**.", "",
              "| output | run 1 fingerprint | run 2 fingerprint | same |", "|---|---|---|---|"]
        L += [f"| {c['output']} | {c['run1']} | {c['run2']} | {'yes' if c['same'] else 'NO'} |" for c in idem["comparisons"]]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="full")
    args = ap.parse_args()
    cfg = load_dq_config()
    (PROJECT_ROOT / "documentation" / "cleaning_rules.md").write_text(rules_doc(cfg), encoding="utf-8")
    out = PROJECT_ROOT / "reports" / ("cleaning_report.md" if args.mode == "full" else f"cleaning_report_{args.mode}.md")
    out.write_text(report(args.mode), encoding="utf-8")
    print(f"wrote documentation/cleaning_rules.md and {out.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
