"""Run all configured data-quality rules on a dataset and report the results.

Reads:   Phase 2 Parquet + ingestion quarantine in HDFS, config/data_quality.yaml
Writes:  HDFS /<base>/dq/violations/ (Parquet, one row per violation, partitioned by rule_id)
         HDFS /<base>/dq/summary.json  and  reports/data_quality_<mode>.json (machine-readable)
         reports/data_quality_report.md (full) or reports/data_quality_report_<mode>.md

The pipeline never reads the generator's injection manifest: detection is based only on the
data and the generic rules. (spark_jobs/dq_evaluate.py compares the results with the manifest
separately, to measure precision and recall.)

NestJS analogy: each rule is a validator; this job is the pipe that runs all validators over
every record and collects the errors instead of stopping at the first one.

Usage: python spark_jobs/data_quality.py --mode full
"""

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pyspark import StorageLevel  # noqa: E402
from pyspark.sql import functions as F  # noqa: E402

from spark_jobs.common import PROJECT_ROOT, get_logger, get_spark, hdfs_uri  # noqa: E402
from spark_jobs.dq_rules import DQData, key_expr, load_dq_config, primary_key, run_rule  # noqa: E402


def samples_for(d: DQData, rule: dict, viol, n: int) -> list:
    """Up to n example violations, with the full offending record where it can be looked up."""
    rows = viol.filter(F.col("rule_id") == rule["id"]).orderBy("record_key").limit(n).collect()
    if not rows:
        return []
    keys = [r["record_key"] for r in rows]
    records = {}
    if rule["check"] in ("unparseable",) or (rule["check"] == "value_range" and rule["params"].get("include_unparseable")):
        q = d.quarantine(rule["table"]).filter(F.col("record_key").isin(keys)).select("record_key", "raw_record").collect()
        records.update({r["record_key"]: r["raw_record"] for r in q})
    if rule["check"] not in ("sequence_integrity", "missing_parent"):
        t = d.table(rule["table"])
        cols = [c for c in t.columns if c != "_source_file"]
        found = (t.withColumn("record_key", key_expr(rule["table"])).filter(F.col("record_key").isin(keys))
                 .select("record_key", F.to_json(F.struct(*cols)).alias("rec")).collect())
        for r in found:
            records.setdefault(r["record_key"], r["rec"])
    return [{"record_key": r["record_key"], "column": r["column"], "observed_value": r["observed_value"],
             "units": r["units"], "record": (records.get(r["record_key"]) or "")[:300]} for r in rows]


def to_markdown(mode, summary, secs, log_file) -> str:
    L = [f"# Data Quality Report - `{mode}` dataset", "",
         f"_Generated by `spark_jobs/data_quality.py --mode {mode}` in {secs:.0f} s (log: `{log_file}`). "
         "Rules and thresholds: `config/data_quality.yaml`; check implementations: `spark_jobs/dq_rules.py`. "
         f"Machine-readable copy: HDFS `{summary['hdfs_summary']}` and `reports/data_quality_{mode}.json`; "
         f"all violating keys: HDFS `{summary['hdfs_violations']}`._", "",
         "**Affected rows** = rows (or groups/IDs for group-level rules) that break the rule; **affected units** counts "
         "the problems themselves (e.g. 3 missing ticket records on one trip = 1 row, 3 units).", "",
         "| rule | defect type | table | severity | check | action | affected rows | affected units | % of table | description |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for r in summary["rules"]:
        pct = f"{r['affected_rows'] / r['table_rows'] * 100:.3f}" if r["table_rows"] else "-"
        L.append(f"| {r['id']} | {r['defect_type']} | {r['table']} | {r['severity']} | {r['check']} | {r['action']} | "
                 f"{r['affected_rows']:,} | {r['affected_units']:,} | {pct} | {r['description']} |")
    L += ["", f"Rules with findings: {sum(r['affected_rows'] > 0 for r in summary['rules'])} of {len(summary['rules'])}.", "",
          "## Sample rows per rule", ""]
    for r in summary["rules"]:
        L += [f"### {r['id']} - {r['defect_type']} ({r['table']}): {r['affected_rows']:,} rows", ""]
        if not r["samples"]:
            L += ["No violations.", ""]
            continue
        L += ["| record_key | column | observed | record |", "|---|---|---|---|"]
        for s in r["samples"]:
            rec = s["record"].replace("|", "/")
            L.append(f"| {s['record_key']} | {s['column']} | {str(s['observed_value']).replace('|', '/')} | `{rec}` |")
        L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="full")
    args = ap.parse_args()
    log, log_path = get_logger(f"data_quality_{args.mode}")
    cfg = load_dq_config()
    P = cfg["params"]
    spark = get_spark("data-quality")
    d = DQData(spark, args.mode)
    t0 = time.perf_counter()

    # One small Spark job per rule, written to its own partition folder (rule_id=<id>). Small plans are
    # faster to optimise, easy to time, and one slow rule cannot stall the others.
    out_viol = hdfs_uri(args.mode, "dq", "violations")
    subprocess.run(["hdfs", "dfs", "-rm", "-r", "-f", "-skipTrash", out_viol], check=True, capture_output=True)
    rule_seconds = {}
    for rule in cfg["rules"]:
        t1 = time.perf_counter()
        (run_rule(d, rule, P).drop("rule_id").coalesce(1)
         .write.mode("overwrite").parquet(f"{out_viol}/rule_id={rule['id']}"))
        rule_seconds[rule["id"]] = round(time.perf_counter() - t1, 1)
        log.info(f"{rule['id']}: checked in {rule_seconds[rule['id']]} s")
    viol = spark.read.parquet(out_viol).persist(StorageLevel.MEMORY_AND_DISK)

    counts = {r["rule_id"]: (r["rows"], r["units"]) for r in
              viol.groupBy("rule_id").agg(F.count("*").alias("rows"), F.sum("units").alias("units")).collect()}
    table_rows = {}
    summary_rules = []
    for rule in cfg["rules"]:
        t = rule["table"]
        if t not in table_rows:
            table_rows[t] = d.table(t).count()
        rows, units = counts.get(rule["id"], (0, 0))
        summary_rules.append({
            "id": rule["id"], "defect_type": rule["defect_type"], "table": t, "severity": rule["severity"],
            "check": rule["check"], "action": rule["action"], "description": rule["description"],
            "params": rule.get("params", {}), "table_rows": table_rows[t], "affected_rows": int(rows),
            "affected_units": int(units or 0), "seconds": rule_seconds[rule["id"]],
            "samples": samples_for(d, rule, viol, P["sample_rows"]),
        })
        log.info(f"{rule['id']} {rule['defect_type']} [{t}]: {int(rows):,} rows, {int(units or 0):,} units")
    secs = time.perf_counter() - t0
    summary = {"mode": args.mode, "seconds": round(secs, 1), "primary_keys": {t: primary_key(t) for t in table_rows},
               "hdfs_violations": out_viol, "hdfs_summary": hdfs_uri(args.mode, "dq", "summary.json"),
               "rules": summary_rules}
    out_json = PROJECT_ROOT / "reports" / f"data_quality_{args.mode}.json"
    out_json.write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
    subprocess.run(["hdfs", "dfs", "-put", "-f", str(out_json), summary["hdfs_summary"]], check=True)
    out_md = PROJECT_ROOT / "reports" / ("data_quality_report.md" if args.mode == "full" else f"data_quality_report_{args.mode}.md")
    out_md.write_text(to_markdown(args.mode, summary, secs, str(log_path.relative_to(PROJECT_ROOT))), encoding="utf-8")
    log.info(f"DQ done: {len(cfg['rules'])} rules, {viol.count():,} violation rows in {secs:.0f} s -> "
             f"{out_md.relative_to(PROJECT_ROOT)}, {out_json.relative_to(PROJECT_ROOT)}, {out_viol}")
    spark.stop()


if __name__ == "__main__":
    main()
