"""Evaluate data-quality detection against the generator's injection manifest (precision / recall).

This is the ONLY Phase 3 script that reads the manifest. The pipeline (profile_data, data_quality,
clean_data) never does; this script runs afterwards and grades it, like a test suite grading an
implementation against known answers.

For each injected defect type (and table):
  injected keys  = data_generator/manifests/<mode>/injection_keys.jsonl.gz
  detected keys  = HDFS /<base>/dq/violations of the rules with the same defect_type
  TP = keys in both (multiset, so a key duplicated twice counts twice), FP = detected - TP, FN = injected - TP
  precision = TP / detected, recall = TP / injected

Special case: `missing_ticket_records` - the injected keys are ticket IDs that were deleted, so they
cannot appear in the data. Detection is count-based (card validations vs ticket rows per trip):
TP = min(detected units, injected rows).

Rules that found something for which nothing was injected (e.g. trip-level time checks) are reported
as extra findings (all of them count as false positives).

Usage: python spark_jobs/dq_evaluate.py --mode full
"""

import argparse
import gzip
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pyspark.sql import functions as F  # noqa: E402

from spark_jobs.common import PROJECT_ROOT, get_logger, get_spark, hdfs_uri  # noqa: E402
from spark_jobs.dq_rules import load_dq_config  # noqa: E402

COUNT_BASED = {"missing_ticket_records"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="full")
    args = ap.parse_args()
    log, log_path = get_logger(f"dq_evaluate_{args.mode}")
    mdir = PROJECT_ROOT / "data_generator" / "manifests" / args.mode
    manifest = json.loads((mdir / "injection_manifest.json").read_text())
    injected = defaultdict(Counter)                    # (defect, table) -> Counter(key)
    with gzip.open(mdir / "injection_keys.jsonl.gz", "rt", encoding="utf-8") as f:
        for line in f:
            k = json.loads(line)
            injected[(k["defect"], k["table"])][k["key"]] += 1

    cfg = load_dq_config()
    rule_defect = {r["id"]: (r["defect_type"], r["table"]) for r in cfg["rules"]}
    spark = get_spark("dq-evaluate")
    viol = spark.read.parquet(hdfs_uri(args.mode, "dq", "violations"))
    detected = defaultdict(Counter)                    # (defect, rule table) -> Counter(key)
    for r in viol.groupBy("rule_id", "record_key").agg(F.sum("units").alias("u")).collect():
        detected[rule_defect[r["rule_id"]]][r["record_key"]] += int(r["u"])
    spark.stop()

    rows, used = [], set()
    for (defect, table), inj in sorted(injected.items()):
        if defect in COUNT_BASED:                      # detected on another table (passenger_counts)
            det_units = sum(sum(c.values()) for (d, _), c in detected.items() if d == defect)
            used |= {k for k in detected if k[0] == defect}
            n_inj = sum(inj.values())
            tp = min(det_units, n_inj)
            rows.append({"defect": defect, "table": table, "injected": n_inj, "detected": det_units, "tp": tp,
                         "fp": det_units - tp, "fn": n_inj - tp, "method": "count"})
            continue
        det = detected.get((defect, table), Counter())
        used.add((defect, table))
        tp = sum((inj & det).values())
        rows.append({"defect": defect, "table": table, "injected": sum(inj.values()), "detected": sum(det.values()),
                     "tp": tp, "fp": sum(det.values()) - tp, "fn": sum(inj.values()) - tp, "method": "key"})
    extra = [{"defect": d, "table": t, "detected": sum(c.values())} for (d, t), c in sorted(detected.items())
             if (d, t) not in used and sum(c.values()) > 0]
    for r in rows:
        r["precision"] = round(r["tp"] / r["detected"], 4) if r["detected"] else None
        r["recall"] = round(r["tp"] / r["injected"], 4) if r["injected"] else None
    injected_types = sorted({r["defect"] for r in rows})
    all_types_found = all(any(x["defect"] == t and x["tp"] > 0 for x in rows) for t in injected_types)

    out_json = PROJECT_ROOT / "reports" / f"dq_evaluation_{args.mode}.json"
    out_json.write_text(json.dumps({"mode": args.mode, "rows": rows, "extra_findings": extra,
                                    "defect_types_injected": len(injected_types),
                                    "defect_types_detected": sum(any(x["defect"] == t and x["tp"] > 0 for x in rows) for t in injected_types)},
                                   indent=2), encoding="utf-8")
    L = [f"# Data-Quality Detection vs Injection Manifest - `{args.mode}`", "",
         f"_Generated by `spark_jobs/dq_evaluate.py --mode {args.mode}` (log `{log_path.relative_to(PROJECT_ROOT)}`). "
         "This script is the only one that reads the manifest; the pipeline itself never does._", "",
         f"Injected defect types: **{len(injected_types)}**, detected (TP > 0): "
         f"**{sum(any(x['defect'] == t and x['tp'] > 0 for x in rows) for t in injected_types)}**.", "",
         "| defect type | table | method | injected | detected | TP | FP | FN | precision | recall |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        L.append(f"| {r['defect']} | {r['table']} | {r['method']} | {r['injected']:,} | {r['detected']:,} | {r['tp']:,} | "
                 f"{r['fp']:,} | {r['fn']:,} | {r['precision'] if r['precision'] is not None else '-'} | "
                 f"{r['recall'] if r['recall'] is not None else '-'} |")
    L += ["", "**Method** `key`: record keys compared one by one. `count`: the injected records were deleted, so only the "
          "number of missing records can be compared (card validations vs ticket rows per trip).", "",
          "## Findings with no matching injection", ""]
    L += ([f"- {e['defect']} [{e['table']}]: {e['detected']:,} rows" for e in extra] or ["None - no rule fired where nothing was injected."])
    misses = [r for r in rows if r["fn"] or r["fp"]]
    L += ["", "## Misses and false positives", ""]
    L += ([f"- {r['defect']} [{r['table']}]: FN {r['fn']:,}, FP {r['fp']:,}" for r in misses] or ["None."])
    out_md = PROJECT_ROOT / "reports" / f"dq_evaluation_{args.mode}.md"
    out_md.write_text("\n".join(L) + "\n", encoding="utf-8")
    for r in rows:
        log.info(f"{r['defect']:28s} [{r['table']:16s}] injected={r['injected']:>7,} detected={r['detected']:>7,} "
                 f"precision={r['precision']} recall={r['recall']}")
    log.info(f"extra findings: {extra}; all injected defect types detected: {all_types_found}")


if __name__ == "__main__":
    main()
