"""Hidden-data readiness report: what the unchanged pipeline found in the hidden_like dataset.

The hidden_like dataset lives in its own HDFS namespace (/urbantransit_hidden_like/...) and went
through exactly the same jobs as the main dataset (ingest_raw, profile_data, data_quality,
clean_data) with no code change - only `--mode hidden_like`. This script summarises:

* unseen categories compared with the main dataset: new stops, routes, vehicles, service
  calendars (timetables) and passengers present in hidden_like but not in full,
* references the hidden data makes to entities it does not define (e.g. unknown vehicles),
* which data-quality rules fired, and which fired only on the hidden data,
* the cleaning reconciliation for the hidden data.

Usage: python spark_jobs/hidden_readiness.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pyspark.sql import functions as F  # noqa: E402

from spark_jobs.common import PROJECT_ROOT, get_logger, get_spark, hdfs_uri  # noqa: E402

ENTITIES = [("stops", "stop_id"), ("routes", "route_id"), ("vehicles", "vehicle_id"),
            ("service_calendar", "service_id"), ("passengers", "passenger_id")]


def main():
    log, log_path = get_logger("hidden_readiness")
    spark = get_spark("hidden-readiness")
    rows = []
    for table, key in ENTITIES:
        full = spark.read.parquet(hdfs_uri("full", "parquet", table)).select(key).distinct()
        hid = spark.read.parquet(hdfs_uri("hidden_like", "parquet", table)).select(key).distinct()
        new = hid.join(full, key, "left_anti")
        examples = [r[0] for r in new.orderBy(key).limit(5).collect()]
        rows.append({"entity": table, "full": full.count(), "hidden_like": hid.count(), "new_in_hidden": new.count(),
                     "examples": examples})
        log.info(f"{table}: {rows[-1]}")
    spark.stop()

    rep = PROJECT_ROOT / "reports"
    dq_full = {r["id"]: r for r in json.loads((rep / "data_quality_full.json").read_text())["rules"]}
    dq_hid = json.loads((rep / "data_quality_hidden_like.json").read_text())["rules"]
    clean_hid = json.loads((rep / "cleaning_metrics_hidden_like.json").read_text())
    ev_path = rep / "dq_evaluation_hidden_like.json"
    ev = json.loads(ev_path.read_text()) if ev_path.exists() else None

    L = ["# Hidden-Data Readiness Report (`hidden_like`)", "",
         f"_Generated by `spark_jobs/hidden_readiness.py` (log `{log_path.relative_to(PROJECT_ROOT)}`). The hidden_like "
         "dataset was uploaded to `/urbantransit_hidden_like/` and processed by the same code as the main dataset "
         "(`ingest_raw.py`, `profile_data.py`, `data_quality.py`, `clean_data.py`) with only `--mode hidden_like`; no file "
         "was edited between the two runs._", "",
         "## Unseen categories (present in hidden_like, absent from the main dataset)", "",
         "| entity | main dataset | hidden_like | new in hidden_like | examples |", "|---|---|---|---|---|"]
    L += [f"| {r['entity']} | {r['full']:,} | {r['hidden_like']:,} | {r['new_in_hidden']:,} | {', '.join(map(str, r['examples']))} |"
          for r in rows]
    L += ["", "New stops, routes, vehicles and service calendars are *valid* new reference data (they are defined in the "
          "hidden dataset's own reference tables), so no rule rejects them; the generic foreign-key rules check references "
          "against whatever reference data arrives with the dataset.", "",
          "## Data-quality rules on hidden_like", "",
          "| rule | defect type | table | hidden_like rows | main dataset rows | fired only on hidden data |", "|---|---|---|---|---|---|"]
    for r in dq_hid:
        f = dq_full.get(r["id"], {}).get("affected_rows", 0)
        L.append(f"| {r['id']} | {r['defect_type']} | {r['table']} | {r['affected_rows']:,} | {f:,} | "
                 f"{'**yes**' if r['affected_rows'] and not f else ''} |")
    L += ["", "## Cleaning reconciliation on hidden_like", "",
          "| table | rows in | clean | removed | quarantined | reconciled |", "|---|---|---|---|---|---|"]
    L += [f"| {t['table']} | {t['rows_in']:,} | {t['rows_clean']:,} | {t['rows_removed']:,} | {t['rows_quarantined']:,} | "
          f"{'PASS' if t['reconciled'] else 'FAIL'} |" for t in clean_hid["tables"]]
    if ev:
        L += ["", "## Detection vs the hidden_like manifest (separate evaluation)", "",
              "| defect type | table | injected | detected | precision | recall |", "|---|---|---|---|---|---|"]
        L += [f"| {r['defect']} | {r['table']} | {r['injected']:,} | {r['detected']:,} | {r['precision']} | {r['recall']} |"
              for r in ev["rows"]]
    (rep / "hidden_readiness_report.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    log.info("wrote reports/hidden_readiness_report.md")


if __name__ == "__main__":
    main()
