"""Build reports/ingestion_report.md from the real run outputs.

Inputs (all produced by actual runs, nothing typed by hand):
  reports/ingestion_metrics_<mode>.json   - spark_jobs/ingest_raw.py
  reports/schema_inference_<mode>.json    - spark_jobs/infer_schemas.py
  data_generator/manifests/<mode>/injection_manifest.json - what was injected
  reports/processing_logs/hdfs_upload_<mode>_*.log         - hdfs_scripts/upload_raw.sh

Usage: python spark_jobs/ingestion_report.py --mode full
"""

import argparse
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def mb(b: int) -> str:
    return f"{b / 1e6:,.1f}"


def build(mode: str) -> str:
    rep = PROJECT_ROOT / "reports"
    metrics = json.loads((rep / f"ingestion_metrics_{mode}.json").read_text())
    inference = json.loads((rep / f"schema_inference_{mode}.json").read_text())
    manifest = json.loads((PROJECT_ROOT / "data_generator" / "manifests" / mode / "injection_manifest.json").read_text())
    upload_logs = sorted((rep / "processing_logs").glob(f"hdfs_upload_{mode}_*.log"))
    upload_tail = upload_logs[-1].read_text().split("== 4) verification (local vs HDFS)")[-1].strip() if upload_logs else "n/a"
    injected = {(d["defect"], d["table"]): d["rows"] for d in manifest["defects"]}
    T = metrics["tables"]

    L = [f"# Ingestion Report - `{mode}` dataset", "",
         f"_Generated by `spark_jobs/ingestion_report.py` from the outputs of the real runs. "
         f"Spark {metrics['spark_version']}, local mode; ingestion log: `{metrics['log_file']}`._", "",
         f"**Overall:** {len(T)} tables ingested in **{metrics['total_seconds']:,.0f} s**; "
         f"rows in = OK + quarantined for every table: **{'yes' if metrics['all_reconciled'] else 'NO'}**.", ""]

    # 1. raw data in HDFS
    L += ["## 1. Raw data in HDFS (upload verification)", "",
          f"`hdfs_scripts/upload_raw.sh {mode}` uploaded the generated files to `/urbantransit/raw/<table>/` and "
          "re-counted them by reading them back out of HDFS:", "", "```", upload_tail, "```", ""]

    # 2. row counts and reconciliation
    L += ["## 2. Row counts and reconciliation", "",
          "`rows in` is counted from the raw text (lines minus one header per CSV file), independently of the typed parser. "
          "`read` is what the explicit-schema reader returned; `OK` rows go to Parquet, `quarantined` rows to "
          "`/urbantransit/quarantine/<table>/`.", "",
          "| table | format | files | rows in | read | OK | quarantined | Parquet rows (read back) | in = OK + quarantined | Parquet = OK |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for t in T:
        L.append(f"| {t['table']} | {t['format']} | {t['raw_files']} | {t['rows_in']:,} | {t['rows_read']:,} | {t['rows_ok']:,} | "
                 f"{t['rows_quarantined']:,} | {t['rows_parquet']:,} | {'PASS' if t['reconciled'] else 'FAIL'} | "
                 f"{'PASS' if t['parquet_matches_ok'] else 'FAIL'} |")
    L.append("")

    # 3. multi-file ingestion
    tk = next(t for t in T if t["table"] == "tickets")
    L += ["## 3. Multiple-file ingestion", "",
          f"Every table is read with one call over its whole HDFS folder. Example: the **{len(tk['rows_per_file'])} monthly "
          f"ticket files** read as one DataFrame ({tk['input_files_read']} input files, {sum(tk['rows_per_file'].values()):,} rows):", "",
          "| file | rows |", "|---|---|"]
    L += [f"| {f} | {n:,} |" for f, n in tk["rows_per_file"].items()]
    L += ["", "Files read per table: " + ", ".join(f"{t['table']} {t['input_files_read']}" for t in T) + ".", ""]

    # 4. quarantine
    L += ["## 4. Type-validation quarantine", "",
          "Rows whose values cannot be converted to the explicit type are kept (PERMISSIVE mode, `_corrupt_record`) and written "
          "with their raw text, source file and the failing column(s). Nothing is dropped silently.", "",
          "| table | quarantined | failing column(s) | example raw record |", "|---|---|---|---|"]
    for t in T:
        if t["rows_quarantined"]:
            cols = ", ".join(f"`{k}` {v:,}" for k, v in t["quarantine_by_column"].items())
            ex = t["quarantine_examples"][0].replace("|", "/") if t["quarantine_examples"] else ""
            L.append(f"| {t['table']} | {t['rows_quarantined']:,} | {cols} | `{ex}` |")
    q = {t["table"]: t["rows_quarantined"] for t in T}
    inv_ts = injected.get(("invalid_timestamps", "tickets"), 0)
    inv_delay = injected.get(("invalid_delay_values", "delays"), 0)
    L += ["", "Cross-check with the injection manifest:", "",
          f"- tickets: quarantined **{q.get('tickets', 0):,}** vs injected invalid timestamps **{inv_ts:,}** -> "
          f"{'exact match' if q.get('tickets', 0) == inv_ts else 'DIFFERENT'}.",
          f"- delays: quarantined **{q.get('delays', 0):,}** of **{inv_delay:,}** injected invalid delay values - the text values "
          "(`unknown`, `n/a`, `#VALUE!`) cannot be parsed as numbers; the out-of-range *numbers* (e.g. 9999) are type-valid, stay in "
          "Parquet and are left for the Phase 3 range checks.",
          "- All other injected defects are type-valid (duplicates, negative counts, unknown IDs, empty IDs, ...) and are kept "
          "unchanged for Phase 3 - ingestion does not clean.", ""]

    # 5. schema inference
    L += ["## 5. Explicit schema vs schema inference", "",
          "Details and reasons: [documentation/schema_inference_comparison.md](../documentation/schema_inference_comparison.md).", "",
          "| table | column | explicit | inferred | values failing explicit type |", "|---|---|---|---|---|"]
    for r in inference:
        for c in r["columns"]:
            if not c["match"]:
                L.append(f"| {r['table']} | {c['column']} | `{c['explicit']}` | `{c['inferred']}` | {c['values_failing_explicit_type']:,} |")
    L += ["", f"Inference time (extra full scan before any work): {sum(r['inference_seconds'] for r in inference):.1f} s in total "
          f"(tickets {next(r['inference_seconds'] for r in inference if r['table'] == 'tickets')} s).", ""]

    # 6. timings
    L += ["## 6. Loading performance", "",
          "| table | rows in | count raw (s) | read + parse (s) | quarantine write (s) | Parquet write (s) | Parquet read-back (s) | total (s) | rows/s |",
          "|---|---|---|---|---|---|---|---|---|"]
    for t in T:
        s = t["timings_s"]
        L.append(f"| {t['table']} | {t['rows_in']:,} | {s['count_raw']} | {s['read_parse']} | {s['quarantine_write']} | "
                 f"{s['parquet_write']} | {s['parquet_readback']} | {sum(s.values()):.1f} | {t['rows_per_second']:,} |")
    big = [t for t in T if t["rows_in"] > 500_000]
    L += ["", f"Large tables ({', '.join(t['table'] for t in big)}): {sum(t['rows_in'] for t in big):,} rows in "
          f"{sum(sum(t['timings_s'].values()) for t in big):.0f} s. Machine: 4 cores / 8 GB WSL2, Spark local[*], driver 4 GB, "
          "8 shuffle partitions, adaptive query execution on.", ""]

    # 7. sizes and partitions
    L += ["## 7. Storage: raw CSV/JSON vs Parquet (Snappy)", "",
          "| table | raw MB | Parquet MB | Parquet / raw | Parquet files | partition column | partitions |",
          "|---|---|---|---|---|---|---|"]
    for t in T:
        L.append(f"| {t['table']} | {mb(t['raw_bytes'])} | {mb(t['parquet_bytes'])} | "
                 f"{t['parquet_bytes'] / max(t['raw_bytes'], 1) * 100:.0f}% | {t['parquet_files']} | "
                 f"{t['partition_column'] or '-'} | {t.get('partitions', '-')} |")
    raw_total, pq_total = sum(t["raw_bytes"] for t in T), sum(t["parquet_bytes"] for t in T)
    L += [f"| **total** | **{mb(raw_total)}** | **{mb(pq_total)}** | **{pq_total / raw_total * 100:.0f}%** | "
          f"{sum(t['parquet_files'] for t in T)} | | |", "",
          "Partitioning strategy and file-size reasoning: [documentation/partition_strategy.md](../documentation/partition_strategy.md).", ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="full")
    args = ap.parse_args()
    out = PROJECT_ROOT / "reports" / ("ingestion_report.md" if args.mode == "full" else f"ingestion_report_{args.mode}.md")
    out.write_text(build(args.mode), encoding="utf-8")
    print(f"wrote {out.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
