"""Profile every table of the Phase 2 Parquet: counts, nulls, distinct values, ranges, distributions.

For each table: row count (+ rows quarantined at ingestion). For each column: null count and %,
distinct count (exact for tables under 200k rows, HyperLogLog estimate with 2% error above),
min/max, and for numeric columns mean, standard deviation and quartiles; for text columns with
few distinct values the top 5 values with counts.

Outputs: reports/data_profile.md (full) or reports/data_profile_<mode>.md,
         reports/data_profile_<mode>.json (machine-readable) and a copy in HDFS /<base>/dq/profile.json.

Laravel analogy: like running `SELECT COUNT(*), COUNT(DISTINCT col), MIN(col), MAX(col) ...` for every
column of every table - one aggregate query per table, executed by Spark.

Usage: python spark_jobs/profile_data.py --mode full
"""

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pyspark.sql import functions as F  # noqa: E402
from pyspark.sql.types import NumericType  # noqa: E402

from spark_jobs.common import PROJECT_ROOT, get_logger, get_spark, hdfs_uri  # noqa: E402
from spark_jobs.dq_rules import DQData  # noqa: E402
from spark_jobs.schemas import SCHEMAS  # noqa: E402

EXACT_DISTINCT_LIMIT = 200_000
TOP_VALUES_MAX_DISTINCT = 30


def profile_table(d: DQData, table: str) -> dict:
    df = d.table(table)
    cols = [f for f in df.schema.fields if f.name != "_source_file"]
    n = df.count()
    exact = n <= EXACT_DISTINCT_LIMIT
    aggs = []
    for f in cols:
        c = F.col(f.name)
        simple = f.dataType.simpleString()
        aggs.append(F.sum(c.isNull().cast("long")).alias(f"{f.name}__nulls"))
        if not simple.startswith("array") and not simple.startswith("struct"):
            aggs.append((F.countDistinct(c) if exact else F.approx_count_distinct(c, 0.02)).alias(f"{f.name}__distinct"))
            aggs.append(F.min(c).cast("string").alias(f"{f.name}__min"))
            aggs.append(F.max(c).cast("string").alias(f"{f.name}__max"))
        if isinstance(f.dataType, NumericType):
            aggs += [F.mean(c).alias(f"{f.name}__mean"), F.stddev(c).alias(f"{f.name}__std"),
                     F.percentile_approx(c, [0.25, 0.5, 0.75], 1000).alias(f"{f.name}__q")]
    row = df.agg(*aggs).first().asDict()
    columns = []
    for f in cols:
        simple = f.dataType.simpleString()
        info = {"column": f.name, "type": simple, "nulls": int(row[f"{f.name}__nulls"]),
                "null_pct": round(row[f"{f.name}__nulls"] / n * 100, 3) if n else 0.0,
                "distinct": row.get(f"{f.name}__distinct"), "distinct_exact": exact,
                "min": row.get(f"{f.name}__min"), "max": row.get(f"{f.name}__max")}
        if isinstance(f.dataType, NumericType):
            q = row[f"{f.name}__q"] or [None, None, None]
            info.update({"mean": row[f"{f.name}__mean"], "std": row[f"{f.name}__std"],
                         "p25": q[0], "median": q[1], "p75": q[2]})
        if simple == "string" and info["distinct"] is not None and info["distinct"] <= TOP_VALUES_MAX_DISTINCT:
            top = df.groupBy(f.name).count().orderBy(F.desc("count"), F.asc(f.name)).limit(5).collect()
            info["top_values"] = [[r[f.name], r["count"]] for r in top]
        columns.append(info)
    try:
        quarantined = d.quarantine(table).count()
    except Exception:                                   # table without an ingestion quarantine folder
        quarantined = 0
    return {"table": table, "rows": n, "rows_quarantined_at_ingestion": quarantined, "columns": columns}


def _fmt(v):
    if v is None:
        return ""
    if isinstance(v, float):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)[:40]


def to_markdown(mode: str, profiles: list, seconds: float, log_file: str) -> str:
    L = [f"# Data Profile - `{mode}` dataset", "",
         f"_Generated by `spark_jobs/profile_data.py --mode {mode}` from the Phase 2 Parquet in HDFS "
         f"in {seconds:.0f} s (log: `{log_file}`). Distinct counts are exact up to {EXACT_DISTINCT_LIMIT:,} rows, "
         "HyperLogLog estimates (about 2% error) above._", "",
         "| table | rows (Parquet) | rows quarantined at ingestion | columns | columns with nulls |", "|---|---|---|---|---|"]
    for p in profiles:
        L.append(f"| {p['table']} | {p['rows']:,} | {p['rows_quarantined_at_ingestion']:,} | {len(p['columns'])} | "
                 f"{sum(c['nulls'] > 0 for c in p['columns'])} |")
    for p in profiles:
        L += ["", f"## {p['table']} ({p['rows']:,} rows)", "",
              "| column | type | nulls | null % | distinct | min | max | mean | median | top values |",
              "|---|---|---|---|---|---|---|---|---|---|"]
        for c in p["columns"]:
            top = "; ".join(f"{v} ({n:,})" for v, n in c.get("top_values", []))
            L.append(f"| {c['column']} | {c['type']} | {c['nulls']:,} | {c['null_pct']} | {_fmt(c['distinct'])} | "
                     f"{_fmt(c['min'])} | {_fmt(c['max'])} | {_fmt(c.get('mean'))} | {_fmt(c.get('median'))} | {top} |")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="full")
    args = ap.parse_args()
    log, log_path = get_logger(f"profile_{args.mode}")
    spark = get_spark("profile")
    d = DQData(spark, args.mode)
    t0 = time.perf_counter()
    profiles = []
    for table in SCHEMAS:
        t1 = time.perf_counter()
        profiles.append(profile_table(d, table))
        log.info(f"{table}: {profiles[-1]['rows']:,} rows profiled in {time.perf_counter() - t1:.1f} s")
    secs = time.perf_counter() - t0
    out_json = PROJECT_ROOT / "reports" / f"data_profile_{args.mode}.json"
    out_json.write_text(json.dumps({"mode": args.mode, "seconds": round(secs, 1), "tables": profiles}, indent=2, default=str))
    out_md = PROJECT_ROOT / "reports" / ("data_profile.md" if args.mode == "full" else f"data_profile_{args.mode}.md")
    out_md.write_text(to_markdown(args.mode, profiles, secs, str(log_path.relative_to(PROJECT_ROOT))), encoding="utf-8")
    # machine-readable copy in HDFS next to the data-quality results
    subprocess.run(["hdfs", "dfs", "-mkdir", "-p", hdfs_uri(args.mode, "dq")], check=True)
    subprocess.run(["hdfs", "dfs", "-put", "-f", str(out_json), hdfs_uri(args.mode, "dq", "profile.json")], check=True)
    log.info(f"wrote {out_md.relative_to(PROJECT_ROOT)}, {out_json.relative_to(PROJECT_ROOT)} and HDFS dq/profile.json "
             f"({len(profiles)} tables, {secs:.0f} s)")
    spark.stop()


if __name__ == "__main__":
    main()
