"""network geometry and gps replay tables

Autogenerated from src/models/network.py (CMD-022), reviewed by hand. Adds route_stops
(route lines for the map) and gps_events (7-day simulated AVL sample, replayed on the map,
indexed by (event_time, vehicle_id)). Both start empty; the loader fills them
(`load_analytics_to_mysql.py --network`).

Revision ID: 13bbf36cd65b
Revises: a7e1187bcc81
Create Date: 2026-09-26 18:13:39.496977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bbf36cd65b'
down_revision = 'a7e1187bcc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=16), nullable=False),
    sa.Column('trip_id', sa.String(length=16), nullable=True),
    sa.Column('route_id', sa.String(length=16), nullable=True),
    sa.Column('stop_id', sa.String(length=16), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('speed_kmh', sa.Double(), nullable=True),
    sa.Column('dq_flags', sa.JSON(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('gps_events', schema=None) as batch_op:
        batch_op.create_index('ix_gps_events_time_vehicle', ['event_time', 'vehicle_id'], unique=False)

    op.create_table('route_stops',
    sa.Column('route_id', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('stop_sequence', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('stop_id', sa.String(length=16), nullable=False),
    sa.Column('distance_from_start_km', sa.Double(), nullable=False),
    sa.Column('scheduled_offset_min', sa.Double(), nullable=False),
    sa.Column('is_timing_point', sa.Boolean(), nullable=False),
    sa.Column('dq_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.stop_id'], ),
    sa.PrimaryKeyConstraint('route_id', 'direction', 'stop_sequence')
    )
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_stops_stop_id'), ['stop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_stops_stop_id'))

    op.drop_table('route_stops')
    with op.batch_alter_table('gps_events', schema=None) as batch_op:
        batch_op.drop_index('ix_gps_events_time_vehicle')

    op.drop_table('gps_events')
    # ### end Alembic commands ###
