"""trip_context route-hour delay history

CMD-028: the served delay model (xgboost v1, retrained) also takes the route/direction/hour
history prior_route_hour_delay_mean and prior_route_hour_severe_rate. Both start NULL;
database/load_model_outputs.py fills them.

Revision ID: 14a50a4cc0a8
Revises: 927e64bd1e92
Create Date: 2026-09-27 18:48:49.475084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a50a4cc0a8'
down_revision = '927e64bd1e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_context', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prior_route_hour_delay_mean', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('prior_route_hour_severe_rate', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_context', schema=None) as batch_op:
        batch_op.drop_column('prior_route_hour_severe_rate')
        batch_op.drop_column('prior_route_hour_delay_mean')

    # ### end Alembic commands ###
