"""model serving tables

Autogenerated from src/models/serving.py and src/models/ml.py (CMD-024), reviewed by hand.
Adds the tables the model-serving API reads (route_daily_boardings, trip_context,
recommendations, pipeline_comparison, route_clusters, python_cluster_profiles) and
`model_metrics.pipeline` (existing rows become "spark"). All start empty;
`database/load_model_outputs.py` and `database/load_model_metrics.py` fill them.

Revision ID: 6e3739ffae4a
Revises: 13bbf36cd65b
Create Date: 2026-09-26 23:26:31.737699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3739ffae4a'
down_revision = '13bbf36cd65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('actual', sa.String(length=32), nullable=True),
    sa.Column('spark_prediction', sa.String(length=32), nullable=True),
    sa.Column('python_prediction', sa.String(length=32), nullable=True),
    sa.Column('spark_value', sa.String(length=255), nullable=True),
    sa.Column('python_value', sa.String(length=64), nullable=True),
    sa.Column('absolute_difference', sa.Double(), nullable=True),
    sa.Column('match', sa.Boolean(), nullable=False),
    sa.Column('agreement_status', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_comparison', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_comparison_agreement_status'), ['agreement_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_comparison_task'), ['task'], unique=False)

    op.create_table('python_cluster_profiles',
    sa.Column('cluster', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('avg_occupancy', sa.Double(), nullable=True),
    sa.Column('avg_delay_minutes', sa.Double(), nullable=True),
    sa.Column('reliability_score', sa.Double(), nullable=True),
    sa.Column('trip_frequency', sa.Double(), nullable=True),
    sa.Column('peak_demand_ratio', sa.Double(), nullable=True),
    sa.Column('load_factor', sa.Double(), nullable=True),
    sa.Column('avg_travel_time', sa.Double(), nullable=True),
    sa.Column('demand_mom_growth', sa.Double(), nullable=True),
    sa.Column('avg_daily_boardings', sa.Double(), nullable=True),
    sa.Column('profile_label', sa.String(length=128), nullable=True),
    sa.Column('routes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cluster')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('estimated_impact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_subject_id'), ['subject_id'], unique=False)

    op.create_table('route_clusters',
    sa.Column('route_id', sa.String(length=16), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    with op.batch_alter_table('route_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_clusters_cluster'), ['cluster'], unique=False)

    op.create_table('route_daily_boardings',
    sa.Column('route_id', sa.String(length=16), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('boardings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('route_id', 'service_date')
    )
    op.create_table('trip_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(length=8), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=16), nullable=True),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('capacity_total', sa.Double(), nullable=True),
    sa.Column('route_type', sa.String(length=32), nullable=True),
    sa.Column('distance_km', sa.Double(), nullable=True),
    sa.Column('planned_runtime_min', sa.Double(), nullable=True),
    sa.Column('headway_min', sa.Double(), nullable=True),
    sa.Column('scheduled_runtime_min', sa.Double(), nullable=True),
    sa.Column('prior_route_crowding_rate', sa.Double(), nullable=True),
    sa.Column('prior_route_delay_mean', sa.Double(), nullable=True),
    sa.Column('trips_observed', sa.Integer(), nullable=False),
    sa.Column('observed_crowding_rate', sa.Double(), nullable=True),
    sa.Column('observed_mean_delay_min', sa.Double(), nullable=True),
    sa.Column('mean_boardings', sa.Double(), nullable=True),
    sa.Column('mean_max_load', sa.Double(), nullable=True),
    sa.Column('mean_occupancy', sa.Double(), nullable=True),
    sa.Column('p90_occupancy', sa.Double(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'direction', 'day_type', 'hour', name='uq_trip_context_cell')
    )
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline', sa.String(length=16), server_default='spark', nullable=False))
        batch_op.create_index(batch_op.f('ix_model_metrics_pipeline'), ['pipeline'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metrics_pipeline'))
        batch_op.drop_column('pipeline')

    op.drop_table('trip_context')
    op.drop_table('route_daily_boardings')
    with op.batch_alter_table('route_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_clusters_cluster'))

    op.drop_table('route_clusters')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_subject_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_priority'))
        batch_op.drop_index(batch_op.f('ix_recommendations_category'))

    op.drop_table('recommendations')
    op.drop_table('python_cluster_profiles')
    with op.batch_alter_table('pipeline_comparison', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_comparison_task'))
        batch_op.drop_index(batch_op.f('ix_pipeline_comparison_agreement_status'))

    op.drop_table('pipeline_comparison')
    # ### end Alembic commands ###
