"""initial backend schema: rbac, audit, ops, reference, analytics, model metrics

Autogenerated by `flask db migrate` from src/models (CMD-019), reviewed by hand.
Creates 43 tables: 30 Phase 5 analytics mirrors (exact Spark types), 3 Phase 1 reference
tables, users/roles/permissions (+2 link tables), audit_log, model_versions, job_runs,
model_metrics and cluster_profiles. All tables start empty; data comes from
database/load_analytics_to_mysql.py and database/load_model_metrics.py.

Revision ID: a7e1187bcc81
Revises: 
Create Date: 2026-09-26 13:07:00.911342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e1187bcc81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('observed_value', sa.Double(), nullable=True),
    sa.Column('expected_value', sa.Double(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/anomalies'
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_anomalies_service_date', ['service_date'], unique=False)

    op.create_table('anomaly_summary',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('signals', sa.BigInteger(), nullable=True),
    sa.Column('entities', sa.BigInteger(), nullable=True),
    sa.Column('dates', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/anomaly_summary'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('cluster_profiles',
    sa.Column('prediction', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('route_load_factor', sa.Double(), nullable=True),
    sa.Column('route_reliability_delay_min', sa.Double(), nullable=True),
    sa.Column('trip_punctuality_rate', sa.Double(), nullable=True),
    sa.Column('avg_trip_boardings', sa.Double(), nullable=True),
    sa.Column('avg_daily_boardings', sa.Double(), nullable=True),
    sa.Column('crowding_rate', sa.Double(), nullable=True),
    sa.Column('bunching_rate', sa.Double(), nullable=True),
    sa.Column('arrival_delay_std_min', sa.Double(), nullable=True),
    sa.Column('routes', sa.Integer(), nullable=True),
    sa.Column('plain_language_label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('prediction')
    )
    op.create_table('delay_by_dimension',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('dimension', sa.String(length=64), nullable=True),
    sa.Column('dim_value', sa.String(length=64), nullable=True),
    sa.Column('trips', sa.BigInteger(), nullable=True),
    sa.Column('evaluated_trips', sa.BigInteger(), nullable=True),
    sa.Column('avg_delay_min', sa.Double(), nullable=True),
    sa.Column('late_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_arrival_delay_min', sa.Double(), nullable=True),
    sa.Column('p90_arrival_delay_min', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/delay_by_dimension'
    )
    op.create_table('delay_by_stop',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=True),
    sa.Column('stop_name', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('stop_type', sa.String(length=64), nullable=True),
    sa.Column('routes_serving', sa.BigInteger(), nullable=True),
    sa.Column('trips_serving', sa.BigInteger(), nullable=True),
    sa.Column('late_records', sa.BigInteger(), nullable=True),
    sa.Column('congestion_records', sa.BigInteger(), nullable=True),
    sa.Column('avg_record_delay_min', sa.Double(), nullable=True),
    sa.Column('top_reason', sa.String(length=64), nullable=True),
    sa.Column('late_record_rate', sa.Double(), nullable=True),
    sa.Column('congestion_record_rate', sa.Double(), nullable=True),
    sa.Column('congestion_rate_pctile', sa.Double(), nullable=True),
    sa.Column('is_bottleneck', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/delay_by_stop'
    )
    with op.batch_alter_table('delay_by_stop', schema=None) as batch_op:
        batch_op.create_index('ix_delay_by_stop_stop_id', ['stop_id'], unique=False)

    op.create_table('delay_congestion_patterns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('early_morning_delay', sa.Double(), nullable=True),
    sa.Column('morning_peak_delay', sa.Double(), nullable=True),
    sa.Column('midday_delay', sa.Double(), nullable=True),
    sa.Column('evening_peak_delay', sa.Double(), nullable=True),
    sa.Column('evening_delay', sa.Double(), nullable=True),
    sa.Column('morning_excess_min', sa.Double(), nullable=True),
    sa.Column('evening_excess_min', sa.Double(), nullable=True),
    sa.Column('congestion_pattern', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/delay_congestion_patterns'
    )
    with op.batch_alter_table('delay_congestion_patterns', schema=None) as batch_op:
        batch_op.create_index('ix_delay_congestion_patterns_route_id', ['route_id'], unique=False)

    op.create_table('delay_top_trips',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=True),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('delay_minutes', sa.Double(), nullable=True),
    sa.Column('delay_severity', sa.String(length=64), nullable=True),
    sa.Column('arrival_delay_min', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/delay_top_trips'
    )
    with op.batch_alter_table('delay_top_trips', schema=None) as batch_op:
        batch_op.create_index('ix_delay_top_trips_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_delay_top_trips_direction', ['direction'], unique=False)
        batch_op.create_index('ix_delay_top_trips_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_delay_top_trips_service_date', ['service_date'], unique=False)
        batch_op.create_index('ix_delay_top_trips_time_period', ['time_period'], unique=False)

    op.create_table('demand_supply_gap',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('days', sa.BigInteger(), nullable=True),
    sa.Column('operated_trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('trips_per_hour', sa.Double(), nullable=True),
    sa.Column('avg_capacity', sa.Double(), nullable=True),
    sa.Column('utilization', sa.Double(), nullable=True),
    sa.Column('p90_load', sa.Integer(), nullable=True),
    sa.Column('denied_per_trip', sa.Double(), nullable=True),
    sa.Column('required_capacity', sa.Numeric(precision=14, scale=1), nullable=True),
    sa.Column('suggested_vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('suggested_capacity', sa.Integer(), nullable=True),
    sa.Column('gap_status', sa.String(length=64), nullable=True),
    sa.Column('suggestion', sa.String(length=64), nullable=True),
    sa.Column('extra_trips_per_hour', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/demand_supply_gap'
    )
    with op.batch_alter_table('demand_supply_gap', schema=None) as batch_op:
        batch_op.create_index('ix_demand_supply_gap_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_demand_supply_gap_direction', ['direction'], unique=False)
        batch_op.create_index('ix_demand_supply_gap_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_demand_supply_gap_time_period', ['time_period'], unique=False)

    op.create_table('eda_peak_days',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('holiday_name', sa.String(length=64), nullable=True),
    sa.Column('est_system_boardings', sa.Double(), nullable=True),
    sa.Column('routes_with_demand', sa.BigInteger(), nullable=True),
    sa.Column('routes_in_service', sa.BigInteger(), nullable=True),
    sa.Column('busiest_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/eda_peak_days'
    )
    with op.batch_alter_table('eda_peak_days', schema=None) as batch_op:
        batch_op.create_index('ix_eda_peak_days_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_eda_peak_days_service_date', ['service_date'], unique=False)

    op.create_table('eda_peak_hours',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('days', sa.BigInteger(), nullable=True),
    sa.Column('trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('avg_boardings_per_trip', sa.Double(), nullable=True),
    sa.Column('est_boardings_per_day', sa.Double(), nullable=True),
    sa.Column('avg_occupancy', sa.Double(), nullable=True),
    sa.Column('peak_rate_asof', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/eda_peak_hours'
    )
    with op.batch_alter_table('eda_peak_hours', schema=None) as batch_op:
        batch_op.create_index('ix_eda_peak_hours_day_class', ['day_class'], unique=False)

    op.create_table('eda_route_delay',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('route_code', sa.String(length=64), nullable=True),
    sa.Column('trips', sa.BigInteger(), nullable=True),
    sa.Column('evaluated_trips', sa.BigInteger(), nullable=True),
    sa.Column('avg_delay_min', sa.Double(), nullable=True),
    sa.Column('late_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('punctuality_rate', sa.Double(), nullable=True),
    sa.Column('avg_arrival_delay_min', sa.Double(), nullable=True),
    sa.Column('most_delayed_rank', sa.Integer(), nullable=True),
    sa.Column('punctuality_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/eda_route_delay'
    )
    with op.batch_alter_table('eda_route_delay', schema=None) as batch_op:
        batch_op.create_index('ix_eda_route_delay_route_id', ['route_id'], unique=False)

    op.create_table('eda_route_demand',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('route_code', sa.String(length=64), nullable=True),
    sa.Column('route_type', sa.String(length=64), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('service_days', sa.BigInteger(), nullable=True),
    sa.Column('est_total_boardings', sa.Double(), nullable=True),
    sa.Column('avg_daily_boardings', sa.Double(), nullable=True),
    sa.Column('avg_demand_coverage', sa.Double(), nullable=True),
    sa.Column('demand_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/eda_route_demand'
    )
    with op.batch_alter_table('eda_route_demand', schema=None) as batch_op:
        batch_op.create_index('ix_eda_route_demand_route_id', ['route_id'], unique=False)

    op.create_table('eda_stop_usage',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=True),
    sa.Column('stop_name', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('stop_type', sa.String(length=64), nullable=True),
    sa.Column('days_open', sa.Integer(), nullable=True),
    sa.Column('card_boardings', sa.BigInteger(), nullable=True),
    sa.Column('card_alightings', sa.BigInteger(), nullable=True),
    sa.Column('est_boardings_per_day', sa.Double(), nullable=True),
    sa.Column('est_alightings_per_day', sa.Double(), nullable=True),
    sa.Column('est_turnover_per_day', sa.Double(), nullable=True),
    sa.Column('usage_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/eda_stop_usage'
    )
    with op.batch_alter_table('eda_stop_usage', schema=None) as batch_op:
        batch_op.create_index('ix_eda_stop_usage_stop_id', ['stop_id'], unique=False)

    op.create_table('flow_direction_demand',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('days', sa.BigInteger(), nullable=True),
    sa.Column('operated_trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('avg_boardings_per_trip', sa.Double(), nullable=True),
    sa.Column('est_boardings_per_day', sa.Double(), nullable=True),
    sa.Column('direction_share', sa.Double(), nullable=True),
    sa.Column('direction_balance', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/flow_direction_demand'
    )
    with op.batch_alter_table('flow_direction_demand', schema=None) as batch_op:
        batch_op.create_index('ix_flow_direction_demand_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_flow_direction_demand_direction', ['direction'], unique=False)
        batch_op.create_index('ix_flow_direction_demand_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_flow_direction_demand_time_period', ['time_period'], unique=False)

    op.create_table('flow_od_pairs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('origin_stop_id', sa.String(length=64), nullable=True),
    sa.Column('destination_stop_id', sa.String(length=64), nullable=True),
    sa.Column('card_journeys', sa.BigInteger(), nullable=True),
    sa.Column('est_journeys', sa.Double(), nullable=True),
    sa.Column('est_journeys_per_day', sa.Double(), nullable=True),
    sa.Column('avg_journey_km', sa.Double(), nullable=True),
    sa.Column('avg_ride_min', sa.Double(), nullable=True),
    sa.Column('routes_used', sa.BigInteger(), nullable=True),
    sa.Column('flow_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/flow_od_pairs'
    )
    with op.batch_alter_table('flow_od_pairs', schema=None) as batch_op:
        batch_op.create_index('ix_flow_od_pairs_destination_stop_id', ['destination_stop_id'], unique=False)
        batch_op.create_index('ix_flow_od_pairs_origin_stop_id', ['origin_stop_id'], unique=False)

    op.create_table('headway_bunching',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('headways', sa.BigInteger(), nullable=True),
    sa.Column('headways_assessed', sa.BigInteger(), nullable=True),
    sa.Column('avg_headway_min', sa.Double(), nullable=True),
    sa.Column('avg_scheduled_gap_min', sa.Double(), nullable=True),
    sa.Column('headway_cv', sa.Double(), nullable=True),
    sa.Column('bunched', sa.BigInteger(), nullable=True),
    sa.Column('gaps', sa.BigInteger(), nullable=True),
    sa.Column('overtakings', sa.BigInteger(), nullable=True),
    sa.Column('bunched_share', sa.Double(), nullable=True),
    sa.Column('gap_share', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/headway_bunching'
    )
    with op.batch_alter_table('headway_bunching', schema=None) as batch_op:
        batch_op.create_index('ix_headway_bunching_direction', ['direction'], unique=False)
        batch_op.create_index('ix_headway_bunching_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_headway_bunching_time_period', ['time_period'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('log_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=128), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('split_type', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Double(), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.Column('validity_flag', sa.String(length=16), nullable=True),
    sa.Column('validity_note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_metrics_source_file'), ['source_file'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metrics_task'), ['task'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', 'algorithm', 'version')
    )
    op.create_table('od_matrix',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('origin_stop_id', sa.String(length=64), nullable=True),
    sa.Column('origin_stop_name', sa.String(length=64), nullable=True),
    sa.Column('destination_stop_id', sa.String(length=64), nullable=True),
    sa.Column('destination_stop_name', sa.String(length=64), nullable=True),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('service_type', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('day_type', sa.String(length=64), nullable=True),
    sa.Column('card_journeys', sa.BigInteger(), nullable=True),
    sa.Column('est_passengers', sa.Double(), nullable=True),
    sa.Column('days_observed', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/od_matrix'
    )
    with op.batch_alter_table('od_matrix', schema=None) as batch_op:
        batch_op.create_index('ix_od_matrix_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_od_matrix_destination_stop_id', ['destination_stop_id'], unique=False)
        batch_op.create_index('ix_od_matrix_direction', ['direction'], unique=False)
        batch_op.create_index('ix_od_matrix_origin_stop_id', ['origin_stop_id'], unique=False)
        batch_op.create_index('ix_od_matrix_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_od_matrix_time_period', ['time_period'], unique=False)

    op.create_table('overcrowding_summary',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('not_measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('low_trips', sa.BigInteger(), nullable=True),
    sa.Column('moderate_trips', sa.BigInteger(), nullable=True),
    sa.Column('high_trips', sa.BigInteger(), nullable=True),
    sa.Column('overcrowded_trips', sa.BigInteger(), nullable=True),
    sa.Column('critical_trips', sa.BigInteger(), nullable=True),
    sa.Column('overload_share', sa.Double(), nullable=True),
    sa.Column('avg_occupancy', sa.Double(), nullable=True),
    sa.Column('max_occupancy', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/overcrowding_summary'
    )
    with op.batch_alter_table('overcrowding_summary', schema=None) as batch_op:
        batch_op.create_index('ix_overcrowding_summary_direction', ['direction'], unique=False)
        batch_op.create_index('ix_overcrowding_summary_route_id', ['route_id'], unique=False)

    op.create_table('passenger_segments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('passenger_id', sa.String(length=64), nullable=True),
    sa.Column('passenger_type', sa.String(length=64), nullable=True),
    sa.Column('age_group', sa.String(length=64), nullable=True),
    sa.Column('journeys', sa.BigInteger(), nullable=True),
    sa.Column('active_days', sa.BigInteger(), nullable=True),
    sa.Column('active_span_weeks', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('active_days_per_week', sa.Numeric(precision=30, scale=3), nullable=True),
    sa.Column('weekday_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('weekend_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('peak_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_journey_km', sa.Double(), nullable=True),
    sa.Column('long_distance_threshold_km', sa.Double(), nullable=True),
    sa.Column('est_journeys_represented', sa.Double(), nullable=True),
    sa.Column('segment', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/passenger_segments'
    )
    op.create_table('peak_period_summary',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('days', sa.BigInteger(), nullable=True),
    sa.Column('trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('asof_trips', sa.BigInteger(), nullable=True),
    sa.Column('avg_boardings_per_trip', sa.Double(), nullable=True),
    sa.Column('est_boardings_per_day', sa.Double(), nullable=True),
    sa.Column('share_of_day', sa.Double(), nullable=True),
    sa.Column('avg_occupancy', sa.Double(), nullable=True),
    sa.Column('peak_rate_asof', sa.Double(), nullable=True),
    sa.Column('is_peak_period', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/peak_period_summary'
    )
    with op.batch_alter_table('peak_period_summary', schema=None) as batch_op:
        batch_op.create_index('ix_peak_period_summary_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_peak_period_summary_time_period', ['time_period'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persistent_overcrowding',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('days_observed', sa.BigInteger(), nullable=True),
    sa.Column('days_overloaded', sa.BigInteger(), nullable=True),
    sa.Column('event_day_overloads', sa.BigInteger(), nullable=True),
    sa.Column('max_occupancy', sa.Double(), nullable=True),
    sa.Column('overload_day_share', sa.Double(), nullable=True),
    sa.Column('overload_pattern', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/persistent_overcrowding'
    )
    with op.batch_alter_table('persistent_overcrowding', schema=None) as batch_op:
        batch_op.create_index('ix_persistent_overcrowding_direction', ['direction'], unique=False)
        batch_op.create_index('ix_persistent_overcrowding_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_persistent_overcrowding_time_period', ['time_period'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('route_performance',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('route_code', sa.String(length=64), nullable=True),
    sa.Column('route_type', sa.String(length=64), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('normal_service_days', sa.BigInteger(), nullable=True),
    sa.Column('excluded_abnormal_days', sa.BigInteger(), nullable=True),
    sa.Column('demand_coverage', sa.Double(), nullable=True),
    sa.Column('med_daily_boardings', sa.Double(), nullable=True),
    sa.Column('med_occupancy', sa.Double(), nullable=True),
    sa.Column('med_p90_occupancy', sa.Double(), nullable=True),
    sa.Column('med_punctuality', sa.Double(), nullable=True),
    sa.Column('med_late_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('med_travel_time_ratio', sa.Double(), nullable=True),
    sa.Column('med_arrival_delay_std', sa.Double(), nullable=True),
    sa.Column('med_underload_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('med_overload_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('persistent_cells', sa.BigInteger(), nullable=True),
    sa.Column('recurring_cells', sa.BigInteger(), nullable=True),
    sa.Column('one_off_cells', sa.BigInteger(), nullable=True),
    sa.Column('event_day_overloads', sa.BigInteger(), nullable=True),
    sa.Column('demand_score', sa.Double(), nullable=True),
    sa.Column('occupancy_score', sa.Double(), nullable=True),
    sa.Column('punctuality_score', sa.Double(), nullable=True),
    sa.Column('delay_frequency_score', sa.Double(), nullable=True),
    sa.Column('travel_time_score', sa.Double(), nullable=True),
    sa.Column('reliability_score', sa.Double(), nullable=True),
    sa.Column('load_score', sa.Double(), nullable=True),
    sa.Column('underutilization_score', sa.Numeric(precision=16, scale=1), nullable=True),
    sa.Column('overcrowding_score', sa.Double(), nullable=True),
    sa.Column('med_overload_severity', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('persistent_cell_share', sa.Double(), nullable=True),
    sa.Column('overcrowding_penalty', sa.Double(), nullable=True),
    sa.Column('composite_score', sa.Double(), nullable=True),
    sa.Column('composite_rank', sa.Double(), nullable=True),
    sa.Column('reliability_rank', sa.Double(), nullable=True),
    sa.Column('route_class', sa.String(length=64), nullable=True),
    sa.Column('class_reason', sa.Text(), nullable=True),
    sa.Column('overcrowded_flag', sa.Boolean(), nullable=True),
    sa.Column('overcrowded_scope', sa.String(length=64), nullable=True),
    sa.Column('overcrowding_location', sa.String(length=64), nullable=True),
    sa.Column('hotspot_stop_id', sa.String(length=64), nullable=True),
    sa.Column('hotspot_share', sa.Double(), nullable=True),
    sa.Column('tricky_case_notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/route_performance'
    )
    with op.batch_alter_table('route_performance', schema=None) as batch_op:
        batch_op.create_index('ix_route_performance_route_id', ['route_id'], unique=False)

    op.create_table('route_reliability',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('scheduled_trips', sa.BigInteger(), nullable=True),
    sa.Column('missed_trips', sa.BigInteger(), nullable=True),
    sa.Column('missed_share', sa.Double(), nullable=True),
    sa.Column('evaluated_trips', sa.BigInteger(), nullable=True),
    sa.Column('on_time_rate', sa.Double(), nullable=True),
    sa.Column('early_arrival_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('late_arrival_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('arrival_delay_std', sa.Double(), nullable=True),
    sa.Column('travel_time_cv', sa.Double(), nullable=True),
    sa.Column('on_time_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/route_reliability'
    )
    with op.batch_alter_table('route_reliability', schema=None) as batch_op:
        batch_op.create_index('ix_route_reliability_route_id', ['route_id'], unique=False)

    op.create_table('schedule_adherence',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('scheduled_trips', sa.BigInteger(), nullable=True),
    sa.Column('missed_trips', sa.BigInteger(), nullable=True),
    sa.Column('completed_trips', sa.BigInteger(), nullable=True),
    sa.Column('early_arrivals', sa.BigInteger(), nullable=True),
    sa.Column('on_time_arrivals', sa.BigInteger(), nullable=True),
    sa.Column('late_arrivals', sa.BigInteger(), nullable=True),
    sa.Column('early_share', sa.Double(), nullable=True),
    sa.Column('on_time_share', sa.Double(), nullable=True),
    sa.Column('late_share', sa.Double(), nullable=True),
    sa.Column('missed_share', sa.Double(), nullable=True),
    sa.Column('intervals_assessed', sa.BigInteger(), nullable=True),
    sa.Column('irregular_intervals', sa.BigInteger(), nullable=True),
    sa.Column('irregular_interval_share', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/schedule_adherence'
    )
    with op.batch_alter_table('schedule_adherence', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_adherence_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_schedule_adherence_route_id', ['route_id'], unique=False)

    op.create_table('segment_summary',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('segment', sa.String(length=64), nullable=True),
    sa.Column('card_holders', sa.BigInteger(), nullable=True),
    sa.Column('share_of_card_holders', sa.Double(), nullable=True),
    sa.Column('avg_journeys', sa.Double(), nullable=True),
    sa.Column('avg_active_days_per_week', sa.Numeric(precision=30, scale=2), nullable=True),
    sa.Column('avg_peak_share', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('avg_journey_km', sa.Double(), nullable=True),
    sa.Column('share_of_est_journeys', sa.Double(), nullable=True),
    sa.Column('most_common_passenger_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/segment_summary'
    )
    op.create_table('service_frequency',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('days', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_trips', sa.BigInteger(), nullable=True),
    sa.Column('operated_trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_trips_per_hour', sa.Double(), nullable=True),
    sa.Column('avg_boardings_per_trip', sa.Double(), nullable=True),
    sa.Column('avg_occupancy', sa.Double(), nullable=True),
    sa.Column('p90_occupancy', sa.Double(), nullable=True),
    sa.Column('overload_share', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('peak_rate_asof', sa.Double(), nullable=True),
    sa.Column('avg_arrival_delay_min', sa.Double(), nullable=True),
    sa.Column('frequency_match', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/service_frequency'
    )
    with op.batch_alter_table('service_frequency', schema=None) as batch_op:
        batch_op.create_index('ix_service_frequency_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_service_frequency_direction', ['direction'], unique=False)
        batch_op.create_index('ix_service_frequency_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_service_frequency_time_period', ['time_period'], unique=False)

    op.create_table('special_event_dates',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('routes_observed', sa.BigInteger(), nullable=True),
    sa.Column('routes_spiking', sa.BigInteger(), nullable=True),
    sa.Column('routes_dropping', sa.BigInteger(), nullable=True),
    sa.Column('max_demand_ratio', sa.Double(), nullable=True),
    sa.Column('holiday_name', sa.String(length=64), nullable=True),
    sa.Column('event_extra_trips', sa.BigInteger(), nullable=True),
    sa.Column('date_status', sa.String(length=64), nullable=True),
    sa.Column('spiking_routes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/special_event_dates'
    )
    with op.batch_alter_table('special_event_dates', schema=None) as batch_op:
        batch_op.create_index('ix_special_event_dates_service_date', ['service_date'], unique=False)

    op.create_table('stop_performance',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=True),
    sa.Column('stop_name', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('stop_type', sa.String(length=64), nullable=True),
    sa.Column('est_boardings_per_day', sa.Double(), nullable=True),
    sa.Column('est_alightings_per_day', sa.Double(), nullable=True),
    sa.Column('est_turnover_per_day', sa.Double(), nullable=True),
    sa.Column('routes_serving', sa.BigInteger(), nullable=True),
    sa.Column('trips_serving_per_day', sa.Double(), nullable=True),
    sa.Column('turnover_per_trip', sa.Double(), nullable=True),
    sa.Column('late_records', sa.BigInteger(), nullable=True),
    sa.Column('avg_record_delay_min', sa.Double(), nullable=True),
    sa.Column('late_record_rate', sa.Double(), nullable=True),
    sa.Column('congestion_record_rate', sa.Double(), nullable=True),
    sa.Column('top_reason', sa.String(length=64), nullable=True),
    sa.Column('is_bottleneck', sa.Boolean(), nullable=True),
    sa.Column('weekday_morning_peak_boardings', sa.Double(), nullable=True),
    sa.Column('weekday_midday_boardings', sa.Double(), nullable=True),
    sa.Column('weekday_evening_peak_boardings', sa.Double(), nullable=True),
    sa.Column('weekday_offpeak_boardings', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/stop_performance'
    )
    with op.batch_alter_table('stop_performance', schema=None) as batch_op:
        batch_op.create_index('ix_stop_performance_stop_id', ['stop_id'], unique=False)

    op.create_table('stops',
    sa.Column('stop_id', sa.String(length=16), nullable=False),
    sa.Column('stop_name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('zone', sa.String(length=8), nullable=False),
    sa.Column('stop_type', sa.String(length=32), nullable=False),
    sa.Column('has_shelter', sa.Boolean(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('dq_flags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('travel_time_analysis',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('completed_trips', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_min', sa.Double(), nullable=True),
    sa.Column('actual_min', sa.Double(), nullable=True),
    sa.Column('excess_min', sa.Double(), nullable=True),
    sa.Column('actual_to_scheduled', sa.Double(), nullable=True),
    sa.Column('std_min', sa.Double(), nullable=True),
    sa.Column('historical_avg_min', sa.Double(), nullable=True),
    sa.Column('vs_historical_min', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/travel_time_analysis'
    )
    with op.batch_alter_table('travel_time_analysis', schema=None) as batch_op:
        batch_op.create_index('ix_travel_time_analysis_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_travel_time_analysis_direction', ['direction'], unique=False)
        batch_op.create_index('ix_travel_time_analysis_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_travel_time_analysis_time_period', ['time_period'], unique=False)

    op.create_table('travel_time_peak_offpeak',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('peak_trips', sa.BigInteger(), nullable=True),
    sa.Column('offpeak_trips', sa.BigInteger(), nullable=True),
    sa.Column('peak_actual_min', sa.Double(), nullable=True),
    sa.Column('offpeak_actual_min', sa.Double(), nullable=True),
    sa.Column('peak_scheduled_min', sa.Double(), nullable=True),
    sa.Column('offpeak_scheduled_min', sa.Double(), nullable=True),
    sa.Column('peak_minus_offpeak_min', sa.Double(), nullable=True),
    sa.Column('peak_penalty_pct', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/travel_time_peak_offpeak'
    )
    with op.batch_alter_table('travel_time_peak_offpeak', schema=None) as batch_op:
        batch_op.create_index('ix_travel_time_peak_offpeak_direction', ['direction'], unique=False)
        batch_op.create_index('ix_travel_time_peak_offpeak_route_id', ['route_id'], unique=False)

    op.create_table('underutilized_services',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('day_class', sa.String(length=64), nullable=True),
    sa.Column('time_period', sa.String(length=64), nullable=True),
    sa.Column('distance_km', sa.Double(), nullable=True),
    sa.Column('days', sa.BigInteger(), nullable=True),
    sa.Column('operated_trips', sa.BigInteger(), nullable=True),
    sa.Column('measured_trips', sa.BigInteger(), nullable=True),
    sa.Column('trips_per_hour', sa.Double(), nullable=True),
    sa.Column('avg_occupancy', sa.Double(), nullable=True),
    sa.Column('p90_occupancy', sa.Double(), nullable=True),
    sa.Column('avg_boardings_per_trip', sa.Double(), nullable=True),
    sa.Column('boardings_per_km', sa.Double(), nullable=True),
    sa.Column('period_median_boardings_per_km', sa.Double(), nullable=True),
    sa.Column('utilization_status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 5 analytics, loaded from hdfs:///urbantransit/analytics/underutilized_services'
    )
    with op.batch_alter_table('underutilized_services', schema=None) as batch_op:
        batch_op.create_index('ix_underutilized_services_day_class', ['day_class'], unique=False)
        batch_op.create_index('ix_underutilized_services_direction', ['direction'], unique=False)
        batch_op.create_index('ix_underutilized_services_route_id', ['route_id'], unique=False)
        batch_op.create_index('ix_underutilized_services_time_period', ['time_period'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(length=16), nullable=False),
    sa.Column('registration_no', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('capacity_seated', sa.Integer(), nullable=False),
    sa.Column('capacity_total', sa.Integer(), nullable=False),
    sa.Column('depot', sa.String(length=64), nullable=False),
    sa.Column('fuel_type', sa.String(length=16), nullable=False),
    sa.Column('commission_date', sa.Date(), nullable=False),
    sa.Column('has_apc', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dq_flags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.String(length=16), nullable=False),
    sa.Column('route_code', sa.String(length=16), nullable=False),
    sa.Column('route_name', sa.String(length=128), nullable=False),
    sa.Column('route_type', sa.String(length=32), nullable=False),
    sa.Column('origin_stop_id', sa.String(length=16), nullable=False),
    sa.Column('destination_stop_id', sa.String(length=16), nullable=False),
    sa.Column('distance_km', sa.Double(), nullable=False),
    sa.Column('base_fare', sa.Double(), nullable=False),
    sa.Column('fare_per_km', sa.Double(), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dq_flags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['destination_stop_id'], ['stops.stop_id'], ),
    sa.ForeignKeyConstraint(['origin_stop_id'], ['stops.stop_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('routes')
    op.drop_table('role_permissions')
    op.drop_table('vehicles')
    op.drop_table('users')
    with op.batch_alter_table('underutilized_services', schema=None) as batch_op:
        batch_op.drop_index('ix_underutilized_services_time_period')
        batch_op.drop_index('ix_underutilized_services_route_id')
        batch_op.drop_index('ix_underutilized_services_direction')
        batch_op.drop_index('ix_underutilized_services_day_class')

    op.drop_table('underutilized_services')
    with op.batch_alter_table('travel_time_peak_offpeak', schema=None) as batch_op:
        batch_op.drop_index('ix_travel_time_peak_offpeak_route_id')
        batch_op.drop_index('ix_travel_time_peak_offpeak_direction')

    op.drop_table('travel_time_peak_offpeak')
    with op.batch_alter_table('travel_time_analysis', schema=None) as batch_op:
        batch_op.drop_index('ix_travel_time_analysis_time_period')
        batch_op.drop_index('ix_travel_time_analysis_route_id')
        batch_op.drop_index('ix_travel_time_analysis_direction')
        batch_op.drop_index('ix_travel_time_analysis_day_class')

    op.drop_table('travel_time_analysis')
    op.drop_table('stops')
    with op.batch_alter_table('stop_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_stop_performance_stop_id')

    op.drop_table('stop_performance')
    with op.batch_alter_table('special_event_dates', schema=None) as batch_op:
        batch_op.drop_index('ix_special_event_dates_service_date')

    op.drop_table('special_event_dates')
    with op.batch_alter_table('service_frequency', schema=None) as batch_op:
        batch_op.drop_index('ix_service_frequency_time_period')
        batch_op.drop_index('ix_service_frequency_route_id')
        batch_op.drop_index('ix_service_frequency_direction')
        batch_op.drop_index('ix_service_frequency_day_class')

    op.drop_table('service_frequency')
    op.drop_table('segment_summary')
    with op.batch_alter_table('schedule_adherence', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_adherence_route_id')
        batch_op.drop_index('ix_schedule_adherence_day_class')

    op.drop_table('schedule_adherence')
    with op.batch_alter_table('route_reliability', schema=None) as batch_op:
        batch_op.drop_index('ix_route_reliability_route_id')

    op.drop_table('route_reliability')
    with op.batch_alter_table('route_performance', schema=None) as batch_op:
        batch_op.drop_index('ix_route_performance_route_id')

    op.drop_table('route_performance')
    op.drop_table('roles')
    with op.batch_alter_table('persistent_overcrowding', schema=None) as batch_op:
        batch_op.drop_index('ix_persistent_overcrowding_time_period')
        batch_op.drop_index('ix_persistent_overcrowding_route_id')
        batch_op.drop_index('ix_persistent_overcrowding_direction')

    op.drop_table('persistent_overcrowding')
    op.drop_table('permissions')
    with op.batch_alter_table('peak_period_summary', schema=None) as batch_op:
        batch_op.drop_index('ix_peak_period_summary_time_period')
        batch_op.drop_index('ix_peak_period_summary_day_class')

    op.drop_table('peak_period_summary')
    op.drop_table('passenger_segments')
    with op.batch_alter_table('overcrowding_summary', schema=None) as batch_op:
        batch_op.drop_index('ix_overcrowding_summary_route_id')
        batch_op.drop_index('ix_overcrowding_summary_direction')

    op.drop_table('overcrowding_summary')
    with op.batch_alter_table('od_matrix', schema=None) as batch_op:
        batch_op.drop_index('ix_od_matrix_time_period')
        batch_op.drop_index('ix_od_matrix_route_id')
        batch_op.drop_index('ix_od_matrix_origin_stop_id')
        batch_op.drop_index('ix_od_matrix_direction')
        batch_op.drop_index('ix_od_matrix_destination_stop_id')
        batch_op.drop_index('ix_od_matrix_day_class')

    op.drop_table('od_matrix')
    op.drop_table('model_versions')
    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metrics_task'))
        batch_op.drop_index(batch_op.f('ix_model_metrics_source_file'))

    op.drop_table('model_metrics')
    op.drop_table('job_runs')
    with op.batch_alter_table('headway_bunching', schema=None) as batch_op:
        batch_op.drop_index('ix_headway_bunching_time_period')
        batch_op.drop_index('ix_headway_bunching_route_id')
        batch_op.drop_index('ix_headway_bunching_direction')

    op.drop_table('headway_bunching')
    with op.batch_alter_table('flow_od_pairs', schema=None) as batch_op:
        batch_op.drop_index('ix_flow_od_pairs_origin_stop_id')
        batch_op.drop_index('ix_flow_od_pairs_destination_stop_id')

    op.drop_table('flow_od_pairs')
    with op.batch_alter_table('flow_direction_demand', schema=None) as batch_op:
        batch_op.drop_index('ix_flow_direction_demand_time_period')
        batch_op.drop_index('ix_flow_direction_demand_route_id')
        batch_op.drop_index('ix_flow_direction_demand_direction')
        batch_op.drop_index('ix_flow_direction_demand_day_class')

    op.drop_table('flow_direction_demand')
    with op.batch_alter_table('eda_stop_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_eda_stop_usage_stop_id')

    op.drop_table('eda_stop_usage')
    with op.batch_alter_table('eda_route_demand', schema=None) as batch_op:
        batch_op.drop_index('ix_eda_route_demand_route_id')

    op.drop_table('eda_route_demand')
    with op.batch_alter_table('eda_route_delay', schema=None) as batch_op:
        batch_op.drop_index('ix_eda_route_delay_route_id')

    op.drop_table('eda_route_delay')
    with op.batch_alter_table('eda_peak_hours', schema=None) as batch_op:
        batch_op.drop_index('ix_eda_peak_hours_day_class')

    op.drop_table('eda_peak_hours')
    with op.batch_alter_table('eda_peak_days', schema=None) as batch_op:
        batch_op.drop_index('ix_eda_peak_days_service_date')
        batch_op.drop_index('ix_eda_peak_days_day_class')

    op.drop_table('eda_peak_days')
    with op.batch_alter_table('demand_supply_gap', schema=None) as batch_op:
        batch_op.drop_index('ix_demand_supply_gap_time_period')
        batch_op.drop_index('ix_demand_supply_gap_route_id')
        batch_op.drop_index('ix_demand_supply_gap_direction')
        batch_op.drop_index('ix_demand_supply_gap_day_class')

    op.drop_table('demand_supply_gap')
    with op.batch_alter_table('delay_top_trips', schema=None) as batch_op:
        batch_op.drop_index('ix_delay_top_trips_time_period')
        batch_op.drop_index('ix_delay_top_trips_service_date')
        batch_op.drop_index('ix_delay_top_trips_route_id')
        batch_op.drop_index('ix_delay_top_trips_direction')
        batch_op.drop_index('ix_delay_top_trips_day_class')

    op.drop_table('delay_top_trips')
    with op.batch_alter_table('delay_congestion_patterns', schema=None) as batch_op:
        batch_op.drop_index('ix_delay_congestion_patterns_route_id')

    op.drop_table('delay_congestion_patterns')
    with op.batch_alter_table('delay_by_stop', schema=None) as batch_op:
        batch_op.drop_index('ix_delay_by_stop_stop_id')

    op.drop_table('delay_by_stop')
    op.drop_table('delay_by_dimension')
    op.drop_table('cluster_profiles')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))

    op.drop_table('audit_log')
    op.drop_table('anomaly_summary')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anomalies_service_date')

    op.drop_table('anomalies')
    # ### end Alembic commands ###
